### ISSUE TITLE
insert-fake-data fails in Windows Python

### ISSUE THREAD

**Issue by mikethebeer** [mfussenegger/cr8#140]
Python 3.5.2 😢 
```
Traceback (most recent call last):
  File "C:\Users\mibe\AppData\Local\Programs\Python\Python35-32\Scripts\cr8-script.py", line 9, in <module>
    load_entry_point('cr8', 'console_scripts', 'cr8')()
  File "c:\users\mibe\sandbox\mikethebeer\cr8\cr8\__main__.py", line 29, in main
    p.dispatch()
  File "C:\Users\mibe\AppData\Local\Programs\Python\Python35-32\lib\site-packages\argh\helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "C:\Users\mibe\AppData\Local\Programs\Python\Python35-32\lib\site-packages\argh\dispatching.py", line 174, in dis
patch
    for line in lines:
  File "C:\Users\mibe\AppData\Local\Programs\Python\Python35-32\lib\site-packages\argh\dispatching.py", line 277, in _ex
ecute_command
    for line in result:
  File "C:\Users\mibe\AppData\Local\Programs\Python\Python35-32\lib\site-packages\argh\dispatching.py", line 260, in _ca
ll
    result = function(*positional, **keywords)
  File "c:\users\mibe\sandbox\mikethebeer\cr8\cr8\insert_fake_data.py", line 248, in insert_fake_data
    loop.add_signal_handler(signal.SIGINT, stop)
  File "C:\Users\mibe\AppData\Local\Programs\Python\Python35-32\lib\asyncio\events.py", line 475, in add_signal_handler
    raise NotImplementedError
NotImplementedError
```

**Comment by mfussenegger** [comment]
I think this only occurs in 0.9,  0.8.1 should work fine.

**Comment by mfussenegger** [comment]
Fixed via https://github.com/mfussenegger/cr8/pull/146
