### ISSUE TITLE
insert-fake-data exists with python error

### ISSUE THREAD

**Issue by joemoe** [mfussenegger/cr8#172]
running with crate 2.1.6 on cr8 0.10.0.

for this schema:

```sql
CREATE TABLE IF NOT EXISTS "ano"."nym" (
   "count" LONG,
   "csp_id" INTEGER,
   "custom1" STRING,
   "custom2" STRING,
   "custom3" STRING,
   "custom4" STRING,
   "custom5" STRING,
   "detecteduser_id" LONG,
   "device_id" INTEGER,
   "dlpbytes" LONG,
   "dlpcount" LONG,
   "downloadedbytes" LONG,
   "eventsummary_id" LONG,
   "fromtime" TIMESTAMP,
   "hash_id" STRING,
   "logprocessortag_id" INTEGER,
   "monitor" INTEGER,
   "protocol" STRING,
   "serviceblocked" INTEGER,
   "tenant_id" INTEGER,
   "timeupdated" TIMESTAMP,
   "totalbytes" LONG,
   "totime" TIMESTAMP,
   "uploadedbytes" LONG,
   "userorip" INTEGER,
   PRIMARY KEY ("detecteduser_id", "fromtime", "eventsummary_id")
);
```

it exits with the following msg.

```
TypeError: 'float' object cannot be interpreted as an integer
```

full output

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/johannes/env/lib/python3.6/site-packages/cr8/insert_fake_data.py", line 137, in _create_bulk_args
    return [row_fun() for i in range(req_size)]
TypeError: 'float' object cannot be interpreted as an integer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/johannes/env/bin/cr8", line 11, in <module>
    sys.exit(main())
  File "/Users/johannes/env/lib/python3.6/site-packages/cr8/__main__.py", line 60, in main
    p.dispatch()
  File "/Users/johannes/env/lib/python3.6/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/Users/johannes/env/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/Users/johannes/env/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/Users/johannes/env/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/Users/johannes/env/lib/python3.6/site-packages/cr8/insert_fake_data.py", line 258, in insert_fake_data
    loop.run_until_complete(tasks)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Users/johannes/env/lib/python3.6/site-packages/cr8/aio.py", line 49, in consume
    raise last_error
  File "/Users/johannes/env/lib/python3.6/site-packages/cr8/aio.py", line 44, in consume
    await task
  File "/Users/johannes/env/lib/python3.6/site-packages/cr8/insert_fake_data.py", line 133, in _exec_many
    return await client.execute_many(stmt, await args_coro)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by joemoe** [comment]
exits after a random number of runs. 
trying to do 100 request with bulksize of 1000.
sometimes 2500, sometimes 1000 rows are inserted.

**Comment by mfussenegger** [comment]
I'm not able to reproduce this.

Could you post the output of `pip list` (If cr8 is installed in a virtualenv, please active that virtualenv before running `pip list`)?

**Comment by joemoe** [comment]
```
aiohttp (2.2.5)
argh (0.26.2)
async-timeout (1.3.0)
backports.csv (1.0.5)
chardet (3.0.4)
cli-helpers (0.2.3)
click (6.7)
configobj (5.0.6)
cr8 (0.10.1)
crate (0.20.1)
dnspython (1.15.0)
email-validator (1.0.2)
Faker (0.8.0)
humanize (0.5.1)
idna (2.6)
multidict (3.1.3)
pgcli (1.7.0)
pgspecial (1.8.0)
pip (9.0.1)
prompt-toolkit (1.0.15)
psycopg2 (2.7.3)
Pygments (2.2.0)
python-dateutil (2.6.1)
setproctitle (1.1.10)
setuptools (28.8.0)
six (1.10.0)
sqlparse (0.2.3)
terminaltables (3.1.0)
toml (0.9.2)
tqdm (4.15.0)
UkPostcodeParser (1.1.1)
urllib3 (1.22)
wcwidth (0.1.7)
yarl (0.12.0)
```
