### ISSUE TITLE
Crate 3.0 refuses to start

### ISSUE THREAD

**Issue by mikethebeer** [mfussenegger/cr8#200]
```bash
$ cr8 run-crate latest-nightly
```

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
Exception in thread "main" java.lang.RuntimeException: Invalid value [1b] for the [cluster.routing.allocation.disk.watermark.low] setting.
at org.elasticsearch.node.internal.CrateSettingsPreparer.validateKnownSettings(CrateSettingsPreparer.java:99)
at org.elasticsearch.node.internal.CrateSettingsPreparer.prepareEnvironment(CrateSettingsPreparer.java:80)
at io.crate.bootstrap.CrateDB.createEnv(CrateDB.java:109)
at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:85)
at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
at org.elasticsearch.cli.Command.main(Command.java:90)
at io.crate.bootstrap.CrateDB.main(CrateDB.java:88)
at io.crate.bootstrap.CrateDB.main(CrateDB.java:81)
Caused by: java.lang.IllegalArgumentException: unable to consistently parse [cluster.routing.allocation.disk.watermark.low=1b], [cluster.routing.allocation.disk.watermark.high=1b], and [cluster.routing.allocation.disk.watermark.flood_stage=95%] as percentage or bytes
at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings.doValidate(DiskThresholdSettings.java:170)
at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings.access$000(DiskThresholdSettings.java:38)
at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings$LowDiskWatermarkValidator.validate(DiskThresholdSettings.java:101)
at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings$LowDiskWatermarkValidator.validate(DiskThresholdSettings.java:95)
at org.elasticsearch.common.settings.Setting.get(Setting.java:361)
at org.elasticsearch.common.settings.Setting.get(Setting.java:342)
at org.elasticsearch.node.internal.CrateSettingsPreparer.validateKnownSettings(CrateSettingsPreparer.java:97)
... 7 more
Caused by: ElasticsearchParseException[failed to parse setting [cluster.routing.allocation.disk.watermark.flood_stage] with value [95%] as a size in bytes: unit is missing or unrecognized]
at org.elasticsearch.common.unit.ByteSizeValue.parseBytesSizeValue(ByteSizeValue.java:175)
at org.elasticsearch.common.unit.ByteSizeValue.parseBytesSizeValue(ByteSizeValue.java:133)
at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings.thresholdBytesFromWatermark(DiskThresholdSettings.java:343)
at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings.doValidateAsBytes(DiskThresholdSettings.java:194)
at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings.doValidate(DiskThresholdSettings.java:159)
... 13 more
Exiting because CrateDB didn't start correctly
```

**Comment by mfussenegger** [comment]
@mikethebeer that's fixed in the latest cr8 version. You'll have to upgrade
